---
- name: "Create namespace {{ item.namespace }}"
  k8s:
    name: "{{ item.namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  with_items: "{{ secrets }}"
  register: output