---
- name: Crear Opaque secrets
  kubernetes.core.k8s:
    namespace: "{{ item.namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
      type: "{{ item.type }}"
      data: "{{ item.data }}"
  with_items: "{{ secrets }}"
  when: item.type == "Opaque"
  register: output

- name: Verficar respuesta
  assert:
    that:
      - output.msg == "All items completed"
      - output.results | length == secrets | length

- name: Verificando cada resultado
  assert:
    that:
      - (item.failed is defined and item.failed == false) or (item.skip_reason is defined and item.skip_reason == "Conditional result was False")
  loop: "{{ output.results }}"
