---
- hosts: localhost
  connection: local
  collections:
    - kubernetes.core.helm
  tasks:
    - name: Crear secrets
      include_vars:
          dir: "local/values"
          files_matching: secrets.yml
    - name: Crear secrets
      include_tasks: tasks/aks_secrets.yml